### ISSUE TITLE
archer init usability overhaul

### ISSUE THREAD

**Issue by kohidave** [aws/amazon-ecs-cli-v2#158]
Init is powerful, but currently pretty confusing to new customers. We should spruce up init to do a better job of explaining concepts, what it's doing and next steps.

- [x] We need to explain what an project, application and environment are #126 
- [x] Guide folks on where to run this command #132 
- [x] After we ask someone if they want to deploy a test env, we should tell them that they can do it later by running `env add` #152 #151 
- [x] Tell folks what we're going to do, when we're going to create a workspace, and provide feedback once we've done it #111 
- [x] Rather than just not asking for a project when you're in a workspace we should say "Looks like you're already in workspace for project _myproject_. We'll use that as your project." #63 #143 #130 
- [x] Let folks create a new project if they're not in an existing ws, but there are existing projects in ssm #134
