### ISSUE TITLE
Define buildspec for the build stage of the pipeline

### ISSUE THREAD

**Issue by efekarakus** [aws/amazon-ecs-cli-v2#346]
## Task

Define the buildspec used in the build phase of the pipeline. 
The buildspec should:
- [x] Build the container image for each application in the workspace (tag = codebuild id)
- [x] Build application cfn templates under the `infrastructure/` directory
- [x] Push the images to each repository (read the *.params files and parse the .ContainerImage field with jq)

**Comment by SoManyHs** [comment]
From previous design:
`Proposed buildspec.yml`

```
version: 0.2
env:
  variables:
    IMAGE_REPO_NAME: <repo-name>
    IMAGE_TAG: release-<uuid> # uuid will be GitHash appended by Archer
    AWS_DEFAULT_REGION: <env-region>
    AWS_ACCOUNT_ID=<account-id>
    ECR_REPO=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
    
phases:
  install:
    runtime-versions:
      docker: 18
      # install archer executable, for to run the package command
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      # - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity | jq '.Account' | tr -d '"')  
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_NAME:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG
  post_build:
    commands:
      # add command for running unit tests here?
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG
```
